name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'Description of the input parameter'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run the job
      run: |
        echo "Running the job with parameter: ${{ github.event.inputs.parameter_name }}"
